# Generated by Django 2.2.6 on 2020-01-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200118_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('beauty', 'Beauty'), ('electroniocs', 'Electroniocs'), ('appliance', 'Appliance')], default='', max_length=50),
        ),
    ]
